services:
  backend:
    build:
      context: ./backend
    container_name: taskflow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: taskflow-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:latest
    container_name: taskflow-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    depends_on:
      - sonar_db
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs

  sonar_db:
    image: postgres:13
    container_name: taskflow-sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

volumes:
  sonar-db-data: